# fly.toml app configuration file generated for personal-website-nik-restless-dew-7542 on 2024-07-21T21:54:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-website-nik-restless-dew-7542'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
