name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Start the website
        run: |
          npm run dev &
          sleep 10
        working-directory: ./frontend

      - name: Wait for the frontend to start
        run: sleep 10

      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "Success!"
